name: Auto-Increment Tag (Patch)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0                            # Ensures git history is fully checked out
          ssh-known-hosts: github.com               # Needed to push to GitHub
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}   # Needed to push to GitHub
          submodules: true                          # Needed since Hugo theme is a submodule

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          git config --global user.name "Anthony Dardano"
          git config --global user.email "anthony.dardano@gemini.com"
          git config --global user.signingkey ~/.ssh/id_ed25519
          git config --global gpg.format ssh
          git config --global commit.gpgsign true
          git config --global push.autoSetupRemote true
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22'

      - name: Install jq
        run: sudo apt-get install jq

      - name: Fetch the latest tag and create new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fetch the latest release
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $LATEST_TAG"

          # Increment the version part of the tag
          BASE_VERSION=$(echo $LATEST_TAG | sed -E 's/(v[0-9]+\.[0-9]+\.)([0-9]+)(-.*)?/\1/')
          PATCH_VERSION=$(echo $LATEST_TAG | sed -E 's/v[0-9]+\.[0-9]+\.([0-9]+)(-.*)?/\1/')
          NEW_PATCH_VERSION=$((PATCH_VERSION + 1))
          NEW_TAG="${BASE_VERSION}${NEW_PATCH_VERSION}"

          # Get the current date in YYYY.MM.DD format and the last commit's short hash
          DATE=$(date -u +"%Y.%m.%d")
          COMMIT_HASH=$(git rev-parse --short HEAD)

          # Create the new full tag
          FULL_TAG="${NEW_TAG}-${DATE}-${COMMIT_HASH}"
          echo "Creating new tag $FULL_TAG"
          git tag $FULL_TAG
          git push origin $FULL_TAG
